server:
  port: 8080

spring:
  application:
    name: userapp
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
